# Generated by Django 4.2.15 on 2024-08-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheraccount',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='courses.discipline', verbose_name='discipline'),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='courses.course', verbose_name='courses'),
        ),
    ]
