# Generated by Django 4.2.15 on 2024-11-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название курса')),
                ('price', models.IntegerField(verbose_name='Цена курса')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(verbose_name='Ссылка на видео')),
                ('title', models.CharField(max_length=100, verbose_name='Название урока')),
                ('courses', models.ManyToManyField(blank=True, null=True, related_name='lessons', to='courses.course', verbose_name='courses')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст задачи')),
                ('answer', models.TextField(verbose_name='Ответ на задачу')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.discipline', verbose_name='discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(verbose_name='Ссылка на видео')),
                ('title', models.CharField(max_length=100, verbose_name='Название вебинара')),
                ('courses', models.ManyToManyField(blank=True, null=True, related_name='webinars', to='courses.course', verbose_name='courses')),
                ('tasks', models.ManyToManyField(blank=True, null=True, related_name='webinars', to='courses.task', verbose_name='tasks')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAnswerWebinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответ на задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_webinars', to='accounts.studentaccount', verbose_name='student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_webinars', to='courses.task', verbose_name='task')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.webinar', verbose_name='webinar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAnswerLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответ на задание')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.lesson', verbose_name='lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_lessons', to='accounts.studentaccount', verbose_name='student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_lessons', to='courses.task', verbose_name='task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='lessons', to='courses.task', verbose_name='tasks'),
        ),
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.discipline', verbose_name='discipline'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_accounts', to='accounts.teacheraccount', verbose_name='teacher'),
        ),
    ]
