# Generated by Django 4.2.15 on 2024-08-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название курса')),
                ('price', models.IntegerField(verbose_name='Цена курса')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(verbose_name='Ссылка на видео')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('schoolwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.schoolwork')),
                ('title', models.CharField(max_length=100, verbose_name='Название урока')),
            ],
            bases=('courses.schoolwork',),
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('schoolwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.schoolwork')),
                ('title', models.CharField(max_length=100, verbose_name='Название вебинара')),
            ],
            bases=('courses.schoolwork',),
        ),
        migrations.CreateModel(
            name='StudentHomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='accounts.studentaccount', verbose_name='student')),
            ],
        ),
    ]
