# Generated by Django 4.2.15 on 2024-11-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='tasks',
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_webinar',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='StudentAnswerWebinar',
        ),
        migrations.DeleteModel(
            name='Webinar',
        ),
    ]
