# Generated by Django 4.2.15 on 2024-09-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('tasks', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='webinars', to='tasks.task', verbose_name='tasks'),
        ),
        migrations.AddField(
            model_name='studentanswerwebinar',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_webinars', to='tasks.task', verbose_name='task'),
        ),
        migrations.AddField(
            model_name='studentanswerwebinar',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.webinar', verbose_name='webinar'),
        ),
        migrations.AddField(
            model_name='studentanswerlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.lesson', verbose_name='lesson'),
        ),
        migrations.AddField(
            model_name='studentanswerlesson',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_lessons', to='tasks.task', verbose_name='task'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='lessons', to='tasks.task', verbose_name='tasks'),
        ),
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.discipline', verbose_name='discipline'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_accounts', to='accounts.teacheraccount', verbose_name='teacher'),
        ),
    ]
