# Generated by Django 4.2.15 on 2024-08-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('courses', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomework',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='homeworks', to='tasks.task', verbose_name='tasks'),
        ),
        migrations.AddField(
            model_name='schoolwork',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='course'),
        ),
        migrations.AddField(
            model_name='schoolwork',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='lessons', to='tasks.task', verbose_name='tasks'),
        ),
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.discipline', verbose_name='discipline'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_accounts', to='accounts.teacheraccount', verbose_name='teacher'),
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='courses.lesson', verbose_name='lesson'),
        ),
    ]
