# Generated by Django 4.2.15 on 2024-10-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='lessons', to='courses.course', verbose_name='courses'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='webinars', to='courses.course', verbose_name='courses'),
        ),
    ]
