# Generated by Django 4.2.15 on 2024-11-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_webinar_courses_remove_webinar_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_lesson',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_webinar',
        ),
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('L', 'Урок'), ('W', 'Вебинар')], default='L', max_length=1),
        ),
    ]
