# Generated by Django 4.2.15 on 2024-08-26 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolwork',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolworks', to='courses.course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='schoolwork',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='schoolworks', to='tasks.task', verbose_name='tasks'),
        ),
    ]
