# Generated by Django 4.2.15 on 2024-08-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_schoolwork_course_alter_schoolwork_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolwork',
            name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webinar',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='webinars', to='courses.course', verbose_name='course'),
            preserve_default=False,
        ),
    ]
