# Generated by Django 4.2.15 on 2024-11-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('courses', '0003_remove_lesson_is_lesson_remove_lesson_is_webinar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswerlesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.studentaccount', verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='studentanswerlesson',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.task', verbose_name='task'),
        ),
    ]
