# Generated by Django 4.2.15 on 2024-11-08 10:57

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_studentanswerlesson_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswerlesson',
            name='answer_photo',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.get_filename_for_answer, verbose_name='Фото решения'),
        ),
    ]
