# Generated by Django 4.2.15 on 2024-08-28 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('courses', '0004_remove_schoolwork_course_lesson_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name='Ответ на задание')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.lesson', verbose_name='lesson')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tasks.task', verbose_name='task')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentHomeWork',
        ),
    ]
