# Generated by Django 4.2.15 on 2024-08-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_studentanswer_delete_studenthomework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответ на задание'),
        ),
    ]
